apiVersion: apps/v1
kind: Deployment
metadata:
  name: tch-pis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tch-pis
  template:
    metadata:
      labels:
        app: tch-pis
    spec:
      containers:
      - name: tch-pis-container
        image: faisalmch/tch-pis-k8s:1.2  # Change to your Docker Hub username
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 3001
        - containerPort: 3002

