apiVersion: v1
kind: Service
metadata:
  name: tch-pis-service
spec:
  type: LoadBalancer
  selector:
    app: tch-pis
  ports:
  - name: auth-service
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: patient-registration
    protocol: TCP
    port: 3001
    targetPort: 3001
  - name: patient-treatment
    protocol: TCP
    port: 3002
    targetPort: 3002

